# Generated by Django 4.1.7 on 2023-03-12 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schema',
            old_name='column_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='max_number',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='min_number',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='order',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='type',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='user',
        ),
        migrations.AddField(
            model_name='schema',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SchemaColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('order', models.IntegerField()),
                ('min_number', models.IntegerField(blank=True, null=True)),
                ('max_number', models.IntegerField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.schema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
