# Generated by Django 4.1.7 on 2023-03-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_schema_column_separator_schema_string_separator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(default='Comma (,)', max_length=15),
        ),
        migrations.AlterField(
            model_name='schema',
            name='string_separator',
            field=models.CharField(default='Double-quote (“)', max_length=15),
        ),
    ]
