# Generated by Django 4.1.7 on 2023-03-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_schema_owner_alter_schema_column_separator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schema',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='schemacolumn',
            name='user',
        ),
    ]
